### ISSUE TITLE
Nvim-tree第一次无法用快捷键呼出

### ISSUE THREAD

**Issue by lmooml** [nshen/InsisVim#13]
您好，首先感谢您的教学，买了您在掘金上的小册子，学到了很多东西。一步一步跟完了，现在体验一下InsisVim.目前发现了2个问题：
1. 在办公室的Lmint系统上，安装配置都没有问题，一次通过。但是Nvim-tree用\<leader\>m 或者\<A-m\>呼不出来，必须使用:NvimTreeToggle命令呼出来一次之后，快捷键就可以正常使用了，其实不影响使用，但是很好奇，想请教下这是怎么回事儿？
2. 在家里的Mac本上，安装配置正常通过，但是编辑文件时，右侧会有一大堆xx% Search in files...的提示，然后界面就卡死了，也无法正常退出，只能关闭Iterm2,想请教下这是哪个插件出了问题？

**Comment by nshen** [comment]
hi，这两个问题，我都还没遇到过。

1.  我没见过Lmint系统，但我这的mac上好像是正常的，你可以试试在 on_attach 里log('xxx')打印一下，看看首次打开 on_attach 会不会执行，或者把 `keymap("n", cfg.keys.toggle, "<CMD>NvimTreeToggle<CR>")` 这行挪到 on_attach 外边试试

https://github.com/nshen/InsisVim/blob/8d511ad78c792f309357faeec09da0242b999a9b/lua/insis/plugins/nvim-tree.lua#L5-L44

2. 我的mac本上正常的，我用的alacritty，iterm2以前也用过，也没见过报错，不知道你编辑的什么文件。截个图看看

**Comment by lmooml** [comment]
1.Lmint是基于ubuntu的发行版，其实也就是ubuntu换个UI吧。我把 keymap("n", cfg.keys.toggle, "<CMD>NvimTreeToggle<CR>") 这行挪到 on_attach 外边，就好了。我打了log，但是不知道在哪儿看日志，也不知道首次打开时on_attach是否执行了，但是挪到外边就好了，估计是一开始没有执行。
2.我装了alacritty，把配置和插件都删掉，重新安装配置了一下insisvim，但是结果一样。好像是lua相关的问题。我编辑其他文件就没事儿。但是一打开lua文件，右侧就有Loading workspace……的提示，当我按下j，k上下移动光标时，就开始一堆提示了。
<img width="1728" alt="截屏2023-05-24 17 55 02" src="https://github.com/nshen/InsisVim/assets/2318423/1d3a917c-e317-4229-a10a-af7bc460680a">

**Comment by nshen** [comment]
1. 哦，那我有空也把它移出来吧 ，一般`:messages` 或者 `:Notifications` 看log

2. 看图应该是 lua lsp 报出来的，可能在搜索什么路径，比较慢，但不至于卡死，可以到mason里把 lua-language-server 删了重装一下试试？
