### ISSUE TITLE
[question] Is there any plan to use lazy.nvim?

### ISSUE THREAD

**Issue by Rongjianying** [nshen/InsisVim#17]
Thanks

**Comment by nshen** [comment]
I think Packer is enough for me, but PR is welcome.

**Comment by nshen** [comment]
done

https://user-images.githubusercontent.com/181506/270083211-ad36e1b1-05f6-47e9-bf2e-6738f539ccce.mp4

https://github.com/nshen/InsisVim/wiki/videos#install
