### ISSUE TITLE
请问该如何定制缩进规则

### ISSUE THREAD

**Issue by tanglong3bf** [nshen/InsisVim#18]
比如说我希望C/C++的缩进为四个空格，具体该在哪里设置。

**Comment by nshen** [comment]
应该在autocmds里添加自定义命令，判断filetype，然后设置

https://github.com/nshen/InsisVim/blob/main/lua/insis/autocmds.lua

应该类似这个语法，具体语句忘记了，你可以查一查

```lua

autocmd("FileType", {
  group = myAutoGroup,
  -- 要改成c/c++的filetype
  pattern = { "markdown" },
  callback = function()
    -- 这里设置缩进
  end,
})
```

**Comment by tanglong3bf** [comment]
我查到clang-format是可以通过命令行参数来指定具体的语法规则，比如`clang-format -style=Google`，或者是指定一个文件的路径。

在`null-ls`的配置中引入了一个`sources`，其中有一项的`name`为`clang-format`。

我猜测通过修改配置文件，来修改这里获取到的`sources`，修改其中的`_opts.args`，进而指定命令行参数。
那么具体应该修改那一个文件呢，是修改`/lua/insis/env/clangd.lua`吗？

**Comment by nshen** [comment]
hi, 我觉得你猜的没错，如果clang-format 支持你需要的格式化规则，应该只修改 `/lua/insis/env/clangd.lua` 的这行就可以

https://github.com/nshen/InsisVim/blob/c74c14deb896c86b2397b4b09e21b4c01cc546d1/lua/insis/env/clangd.lua#L38C60-L38C60

在 返回的 builtin 加上参数，类似这样

```lua
return { null_ls.builtins.formatting.clang_format.with({ extra_args = { "-style","Google" } }) }
```

你可以试一下看看是否可以。

加参数的文档：

https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md#arguments

默认返回的配置是这个：

https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting/clang_format.lua

**Comment by tanglong3bf** [comment]
试过了，可以的。
