### ISSUE TITLE
Failed to install Hiphish/nvim-ts-rainbow2,有人遇到过吗

### ISSUE THREAD

**Issue by vectorstone** [nshen/InsisVim#19]
不清楚这个是哪个插件,提示安装失败,有人遇到过吗
![image](https://github.com/nshen/InsisVim/assets/39456045/769e7563-f12d-45fe-b411-a6948d868954)
背景:
win11 WSL2 Ubuntu18.04发行版

**Comment by nshen** [comment]
我觉得先删掉，然后再重装就好了吧

**Comment by nshen** [comment]
在最新版本里 nvim-ts-rainbow2 已经被删掉了
