### ISSUE TITLE
老哥,telescope 在大文件中禁用 treesiiter 如果搞定

### ISSUE THREAD

**Issue by HUAHUAI23** [nshen/InsisVim#2]
https://github.com/nvim-telescope/telescope.nvim/issues/2247

这个问题, 在大文件中用telescope的lsp goto definination和 lsp goto ref, 要等待一些时间,原因是telescope默认调用treesiiter来进行文件高亮渲染

**Comment by nshen** [comment]
没怎么看过大文件，把命令映射成 `:TSDisable highlight<CR>` + lsp goto xxx 可行么？

**Comment by HUAHUAI23** [comment]
不太行🤣只要装了treesiiter 这个插件 telescope就会跑过去调用它

**Comment by HUAHUAI23** [comment]
刚刚邮件提醒了我这个
这个问题我之前解决了 哈哈
参考 <https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#previewers>
在大文件中 telescope 的preview 不用treesiiter高亮用自带的vim 正则高亮
```lua
local previewers = require("telescope.previewers")
local putils = require("telescope.previewers.utils")
local pfiletype = require("plenary.filetype")
local new_maker = function(filepath, bufnr, opts)
	opts = opts or {}
	if opts.use_ft_detect == nil then
		opts.use_ft_detect = true
	end

	filepath = vim.fn.expand(filepath)
	local ft = pfiletype.detect(filepath, {})
	local ok, stats = pcall(vim.loop.fs_stat, filepath)
	if ok and stats and stats.size > commConf.largefileEdge then
		opts.use_ft_detect = false
		putils.regex_highlighter(bufnr, ft)
	end
	previewers.buffer_previewer_maker(filepath, bufnr, opts)
end
```
然后在telescope中的配置加这个
![image](https://user-images.githubusercontent.com/43649186/211998767-3d1ed1a4-87f7-4f7c-8e32-991e07f50da1.png)
