### ISSUE TITLE
怎么开启C++、Lua语言代码开发功能？

### ISSUE THREAD

**Issue by SuperCodeFarmers** [nshen/InsisVim#23]
博主你好，我下载了你的项目，我没打开一个文件，都会提示
“Spawning language server with cmd: `lua-language-server` failed. The language server is either not installed, missing from PATH, or not executable.│”
这个问题怎么解决？
代码开发功能，我看你的README中写的在最外层的init.lua文件中添加了
```lua
require("insis").setup({
  golang = {
    enable = true,
    lsp = "gopls",
    linter = "golangci-lint",
    formatter = "gofmt",
    format_on_save = true,
  },
})
```
直接把CPU跑到了100%。
请问怎么开启代码开发功能

**Comment by nshen** [comment]
默认启动时会安装 `lua-language-server`，你有可能没有全局科学上网，导致安装失败了
运行 `:Mason` 重新安装一下这个应该就好了
<img width="665" alt="image" src="https://github.com/nshen/InsisVim/assets/181506/8de38bb7-aeee-49e0-b898-a22a2aca7a29">
