### ISSUE TITLE
do nothing with command "gd" and "gr"

### ISSUE THREAD

**Issue by HughYZJD** [nshen/InsisVim#29]
Hello everyone, I installed nvim according to the tutorial, but when using the commands gd and gr, there was no response, that is, I was unable to view the definition and references of functions. Other functions are currently being tested normally！

**Comment by nshen** [comment]
Hi, what language are you using ? gd gr is bound to the language server, can you check if lsp is enabled?

`:LspInfo`

<img width="766" alt="image" src="https://github.com/nshen/InsisVim/assets/181506/44a61f61-22b1-4228-8331-bc78c1cceb53">

**Comment by HughYZJD** [comment]
/
<img width="766" alt="1707111979531" src="https://github.com/nshen/InsisVim/assets/26761239/669c288a-1804-40da-80ab-a80f0155e588">
 
hi,nshen

Can you help me check if there are any issues with my configuration? Thank you very much！！

**Comment by HughYZJD** [comment]
hi,nshen,Thank you very much for the prompt. It is currently working normally！
<img width="713" alt="1" src="https://github.com/nshen/InsisVim/assets/26761239/10f3b649-9903-4c1d-acec-ff8e7119b78a">
But the code has given a lot of errors, can you give some hints，
<img width="663" alt="2" src="https://github.com/nshen/InsisVim/assets/26761239/b200d4a3-9936-4b96-ae9b-92d1a7c4b097">
Thank you again！！

**Comment by nshen** [comment]
Sorry I know nothing about C.  HI @charles1614 can you help ?

**Comment by nshen** [comment]
HI, I think it is because the LSP didn't detect your root folder. If it is only working in the current file.

Make sure you have one of the following files in your root folder.

```
'.clangd',
'.clang-tidy',
'.clang-format',
'compile_commands.json',
'compile_flags.txt',
'configure.ac',
'.git'
```

**Comment by HughYZJD** [comment]
HI，nshen
    Thank you for your answer.
    Does this root folder refer to the folder of the entire code project，I ran the "git init. ", but it still doesn't work properly!
<img width="578" alt="1708131014974" src="https://github.com/nshen/InsisVim/assets/26761239/1f698ac6-e1a8-4a09-b2a0-58a31f776b1c">
