### ISSUE TITLE
错误提示：system_open failed to spawn command 'wsl-open' : ENOENT: no such file or directory

### ISSUE THREAD

**Issue by qianb08** [nshen/InsisVim#7]
在目录树打开文件或目录时会出现此错误提示
![image](https://user-images.githubusercontent.com/117363038/214205281-d7a4fbcc-2b5f-441b-9371-172b2dde0166.png)

**Comment by nshen** [comment]
Hi, 我这里习惯用`o`来打开编辑文件，因此我设置`回车键`为用系统打开，所以按 o 就好了，也可以根据需要改一下这两行

https://github.com/nshen/InsisVim/blob/e1cbd65d081574965c227aa1cffa6474252695fb/lua/insis/config.lua#L140-L142

wsl 中用系统打开文件需要依赖 [wsl-open](https://www.npmjs.com/package/wsl-open)

可以命令行安装一下

`sudo npm install -g wsl-open`

**Comment by qianb08** [comment]
感谢您的回复，问题解决了

**Comment by qianb08** [comment]
> Hi, 我这里习惯`o`用来打开编辑文件，因此我`回车键`设置成了用系统打开，所以按o就好了，也可以根据需要改一下这两条路
> 
> https://github.com/nshen/InsisVim/blob/e1cbd65d081574965c227aa1cffa6474252695fb/lua/insis/config.lua#L140-L142
> 
> wsl 中用系统打开文件需要依赖[wsl-open](https://www.npmjs.com/package/wsl-open)
> 
> 可以命命令安装一下
> 
> `sudo npm install -g wsl-open`

感谢您的回复，问题解决了，谢谢
